version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"  # Еженедельно (в понедельник)
    open-pull-requests-limit: 10  # Максимум 10 открытых PR одновременно
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
